#!/bin/bash

TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB_DIR="${TEST_DIR}/lib"
MODULES_DIR="$(readlink -f "${TEST_DIR}/../node_modules")"
EVENT_DIR="$(readlink -f "${TEST_DIR}/../")"

mkdir -p "${LIB_DIR}"
mkdir -p "${MODULES_DIR}"

pushd "${EVENT_DIR}"
    npm install --silent
popd

if [[ ! -a "${LIB_DIR}/expect.js" ]]; then
    wget \
    https://raw.githubusercontent.com/LearnBoost/expect.js/master/index.js \
    -O "${LIB_DIR}/expect.js" -q
fi

if [[ ! -a "${LIB_DIR}/mocha.js" ]]; then
    wget https://raw.githubusercontent.com/visionmedia/mocha/master/mocha.js \
    -O "${LIB_DIR}/mocha.js" -q
fi

if [[ ! -a "${LIB_DIR}/mocha.css" ]]; then
    wget https://raw.githubusercontent.com/visionmedia/mocha/master/mocha.css \
    -O "${LIB_DIR}/mocha.css" -q
fi

if [[ ! -a "${LIB_DIR}/modelo.js" ]]; then
    ln -s "${MODULES_DIR}/modelo/modelo/modelo.js" "${LIB_DIR}/modelo.js"
fi

if [[ ! -a "${LIB_DIR}/defer.js" ]]; then
    ln -s "${MODULES_DIR}/deferjs/defer/defer.js" "${LIB_DIR}/defer.js"
fi

if [[ ! -a "${MODULES_DIR}/eventjs" ]]; then
    ln -s "${EVENT_DIR}" "${MODULES_DIR}/eventjs"
fi

if [[ ! -a "${LIB_DIR}/event.js" ]]; then
    ln -s "${EVENT_DIR}/event/event.js" "${LIB_DIR}/event.js"
fi

if [[ ! -a "${MODULES_DIR}/expect.js" ]]; then
    ln -s "${LIB_DIR}/expect.js" "${MODULES_DIR}/expect.js"
fi
